- name: default
  run_list:
    - recipe[blockdevice-test::default]
  verifier:
    inspec_tests:
      - path: test/integration/default
    inspec:
  attributes:
    blockdevice_test:
      volume1:
        blockdevice_volume_group:
          block_device: /dev/xvdb
          type: gpt
        blockdevice_volume_partition:
          block_device: /dev/xvdb
          fs_type: 8300
          flags:
            - boot
          partition_name: test1
          offset: 1048576
          size: 1048576
      volume2:
        blockdevice_volume_group:
          block_device: /dev/xvdc
          type: msdos
        blockdevice_volume_partition:
          block_device: /dev/xvdc
          fs_type: 0700
          flags:
            - boot
          partition_type: primary
          offset: 1048576
          size: 1048576
