name             'blockdevice'
maintainer       'Criteo - SRE Core Infra'
maintainer_email 'sre-core-infra@criteo.com'
license          'All rights reserved'
description      'Blockdevice management'
long_description 'Blockdevice management'
issues_url       'https://github.com/criteo-cookbooks/blockdevice/issues'
source_url       'https://github.com/criteo-cookbooks/blockdevice'
version          '0.0.1'
supports         'centos'
supports         'windows'
